function x04_01_2020 = importfile2(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  X04_01_2020 = IMPORTFILE2(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  X04_01_2020 = IMPORTFILE2(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  x04_01_2020 = importfile2("/MATLAB Drive/jhudata/04-01-2020.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Nov-2020 11:28:03

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Country_Region", "Last_Update", "Lat", "Long_", "Confirmed", "Deaths", "Recovered", "Var11", "Var12"];
opts.SelectedVariableNames = ["Country_Region", "Last_Update", "Lat", "Long_", "Confirmed", "Deaths", "Recovered"];
opts.VariableTypes = ["string", "string", "string", "categorical", "datetime", "double", "double", "double", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var11", "Var12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Country_Region", "Var11", "Var12"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Last_Update", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
x04_01_2020 = readtable(filename, opts);

end