function Eucountries = importfile3(filename, dataLines)
    %IMPORTFILE3 Import data from a text file
    %  EUCOUNTRIES = IMPORTFILE3(FILENAME) reads data from text file
    %  FILENAME for the default selection.  Returns the data as a table.
    %
    %  EUCOUNTRIES = IMPORTFILE3(FILE, DATALINES) reads data for the
    %  specified row interval(s) of text file FILENAME. Specify DATALINES as
    %  a positive scalar integer or a N-by-2 array of positive scalar
    %  integers for dis-contiguous row intervals.
    %
    %  Example:
    %  Eucountries = importfile3("/MATLAB Drive/assignment1/Eucountries.csv", [2, Inf]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 16-Nov-2020 14:33:39
    
    %% Input handling
    
    % If dataLines is not specified, define defaults
    if nargin < 2
        dataLines = [2, Inf];
    end
    
    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 1);
    
    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = ",";
    
    % Specify column names and types
    opts.VariableNames = "Country_Region";
    opts.VariableTypes = "string";
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Specify variable properties
    opts = setvaropts(opts, "Country_Region", "WhitespaceRule", "preserve");
    opts = setvaropts(opts, "Country_Region", "EmptyFieldRule", "auto");
    
    % Import the data
    Eucountries = readtable(filename, opts);
    
end